version: '3'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
  mongodb:
    image: mongo:7.0.6
    ports:
    - "27017:27017"
    volumes:
    - mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  mongodata:
